# Generated by Django 3.2.5 on 2023-03-07 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='текст кнопки')),
                ('reaction', models.TextField(verbose_name='реакция')),
            ],
        ),
        migrations.CreateModel(
            name='BotClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='наименование университета')),
                ('activity', models.BooleanField(verbose_name='activity')),
            ],
        ),
        migrations.CreateModel(
            name='BotDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='имя текста')),
                ('value', models.TextField(verbose_name='текст')),
            ],
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='id пользователя')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='имя пользователя')),
                ('initial_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата первого обращения')),
                ('last_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата последнего обращения')),
                ('counter', models.IntegerField(default=1, verbose_name='количество обращений')),
            ],
        ),
    ]
