# Generated by Django 3.2.5 on 2023-02-06 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Words',
        ),
    ]
