# Generated by Django 3.2.5 on 2023-03-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255, verbose_name='access_token')),
                ('refresh_token', models.CharField(max_length=255, verbose_name='refresh_token')),
            ],
        ),
    ]
