# Generated by Django 3.2.5 on 2023-02-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot_app', '0002_delete_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='user_id')),
                ('first_name', models.CharField(max_length=100, verbose_name='first_name')),
                ('username', models.CharField(max_length=100, verbose_name='first_name')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('data', models.CharField(max_length=200, verbose_name='data')),
            ],
        ),
    ]
