# Generated by Django 3.2.5 on 2023-03-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0002_tokentable'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokentable',
            name='name',
            field=models.CharField(default='Token', max_length=200, unique=True, verbose_name='Token'),
            preserve_default=False,
        ),
    ]
