# Generated by Django 3.2.5 on 2023-02-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0003_botdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botdata',
            name='data',
        ),
        migrations.RemoveField(
            model_name='botdata',
            name='first_name',
        ),
        migrations.AddField(
            model_name='botdata',
            name='chat_msg',
            field=models.CharField(default=0, max_length=4096, verbose_name='chat_msg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='botdata',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='botdata',
            name='username',
            field=models.CharField(max_length=100, verbose_name='username'),
        ),
    ]
