# Generated by Django 3.2.5 on 2023-03-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0003_tokentable_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokentable',
            old_name='access_token',
            new_name='token',
        ),
        migrations.RemoveField(
            model_name='tokentable',
            name='refresh_token',
        ),
        migrations.AlterField(
            model_name='tokentable',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Token type'),
        ),
    ]
