# Generated by Django 3.2.5 on 2023-02-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0004_auto_20230208_1622'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BotData',
            new_name='BotUsers',
        ),
    ]
