# Generated by Django 3.2.5 on 2023-02-08 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0005_rename_botdata_botusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botusers',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
