# Generated by Django 3.2.5 on 2023-03-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0005_auto_20230322_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationtable',
            name='num_users',
            field=models.IntegerField(default=1),
        ),
    ]
