# Generated by Django 3.2.5 on 2023-03-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0006_alter_publicationtable_num_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationtable',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='publicationtable',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/telegram_img', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='publicationtable',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='publicationtable',
            name='num_users',
            field=models.IntegerField(default=1, verbose_name='Количество отправок'),
        ),
        migrations.AlterField(
            model_name='publicationtable',
            name='status',
            field=models.CharField(choices=[('запланирована', 'запланирована'), ('отправлена', 'отправлена')], max_length=13, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='publicationtable',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
