# Generated by Django 3.2.5 on 2023-02-08 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0006_alter_botusers_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botusers',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
