# Generated by Django 3.2.5 on 2023-03-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0007_auto_20230322_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationtable',
            name='status',
            field=models.CharField(default='запланирована', max_length=13, verbose_name='Статус'),
        ),
    ]
