# Generated by Django 3.2.5 on 2023-02-08 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0007_alter_botusers_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botusers',
            name='chat_msg',
        ),
    ]
