# Generated by Django 3.2.5 on 2023-03-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0008_alter_publicationtable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='initial_date',
            field=models.DateTimeField(auto_now=True, verbose_name='дата первого обращения'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='last_date',
            field=models.DateTimeField(auto_now=True, verbose_name='дата последнего обращения'),
        ),
        migrations.AlterField(
            model_name='publicationtable',
            name='num_users',
            field=models.IntegerField(default=2, verbose_name='Количество отправок'),
        ),
    ]
