# Generated by Django 3.2.5 on 2023-02-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0009_botbuttons_botclients_botdictionary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BotButtons',
            new_name='BotButton',
        ),
        migrations.RenameModel(
            old_name='BotClients',
            new_name='BotClient',
        ),
        migrations.RenameModel(
            old_name='BotUsers',
            new_name='BotUser',
        ),
    ]
