# Generated by Django 3.2.5 on 2023-03-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0009_auto_20230323_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationtable',
            name='num_users',
            field=models.IntegerField(default=1, verbose_name='Количество отправок'),
        ),
    ]
