# Generated by Django 3.2.5 on 2023-02-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0010_auto_20230208_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botclient',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='name'),
        ),
    ]
