# Generated by Django 3.2.5 on 2023-03-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0010_alter_publicationtable_num_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationtable',
            name='num_users',
            field=models.IntegerField(verbose_name='Количество отправок'),
        ),
    ]
