# Generated by Django 3.2.5 on 2023-03-24 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0011_alter_publicationtable_num_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='initial_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='дата первого обращения'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='дата последнего обращения'),
        ),
    ]
