# Generated by Django 3.2.5 on 2023-02-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0011_alter_botclient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botbutton',
            name='text',
        ),
        migrations.AddField(
            model_name='botbutton',
            name='btns',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
