# Generated by Django 3.2.5 on 2023-03-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0013_auto_20230324_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='user_id',
            field=models.IntegerField(verbose_name='id пользователя'),
        ),
    ]
