# Generated by Django 3.2.5 on 2023-02-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0014_alter_botbutton_btns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botbutton',
            name='btns',
            field=models.JSONField(default=dict, verbose_name='btns'),
        ),
    ]
