# Generated by Django 3.2.5 on 2023-03-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0014_alter_botuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationtable',
            name='num_sent',
            field=models.IntegerField(default=0, verbose_name='Количество отправок'),
        ),
        migrations.AlterField(
            model_name='publicationtable',
            name='num_users',
            field=models.IntegerField(verbose_name='Количество потенциальных получателей'),
        ),
    ]
