# Generated by Django 3.2.5 on 2023-03-27 06:18

import bot_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0015_auto_20230327_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationtable',
            name='num_users',
            field=models.IntegerField(default=bot_app.models.PublicationTable.count_num_users, verbose_name='Количество потенциальных получателей'),
        ),
    ]
