# Generated by Django 3.2.5 on 2023-03-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0016_alter_publicationtable_num_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='botbutton',
            name='sort_id',
            field=models.IntegerField(default=0, verbose_name='сортировка'),
        ),
    ]
