# Generated by Django 3.2.5 on 2023-02-10 05:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0016_rename_username_botuser_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botuser',
            old_name='date',
            new_name='initial_date',
        ),
        migrations.AddField(
            model_name='botuser',
            name='counter',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='botuser',
            name='last_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
