# Generated by Django 3.2.5 on 2023-02-10 06:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0017_auto_20230210_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botbutton',
            name='btns',
            field=models.TextField(verbose_name='текст / реакция'),
        ),
        migrations.AlterField(
            model_name='botbutton',
            name='name',
            field=models.CharField(max_length=200, verbose_name='имя кнопки'),
        ),
        migrations.AlterField(
            model_name='botclient',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='наименование университета'),
        ),
        migrations.AlterField(
            model_name='botdictionary',
            name='name',
            field=models.CharField(max_length=200, verbose_name='имя текста'),
        ),
        migrations.AlterField(
            model_name='botdictionary',
            name='value',
            field=models.TextField(verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='counter',
            field=models.IntegerField(default=1, verbose_name='количество обращений'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='initial_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата первого обращения'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='last_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата последнего обращения'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='name',
            field=models.CharField(max_length=100, verbose_name='имя пользователя'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='user_id',
            field=models.CharField(max_length=100, verbose_name='id пользователя'),
        ),
    ]
