# Generated by Django 3.2.5 on 2023-02-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0018_auto_20230210_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botbutton',
            name='btns',
            field=models.TextField(verbose_name='текст'),
        ),
    ]
