# Generated by Django 3.2.5 on 2023-02-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0019_alter_botbutton_btns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botbutton',
            name='name',
            field=models.CharField(max_length=200, verbose_name='текст кнопки'),
        ),
    ]
