# Generated by Django 3.2.5 on 2023-02-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0020_alter_botbutton_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botdictionary',
            name='value',
            field=models.TextField(verbose_name='реакция'),
        ),
    ]
