# Generated by Django 3.2.5 on 2023-02-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0021_alter_botdictionary_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botbutton',
            name='btns',
        ),
        migrations.AddField(
            model_name='botbutton',
            name='reaction',
            field=models.TextField(default=0, verbose_name='реакция'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='botdictionary',
            name='value',
            field=models.TextField(verbose_name='текст'),
        ),
    ]
