# Generated by Django 3.2.5 on 2023-02-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0022_auto_20230210_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='имя пользователя'),
        ),
    ]
